### PR TITLE
Initial outline of documentation 

### PR DESCRIPTION
**Pull request by googley42**
initial outline of documentation which focuses on structure. Index.md will be refined later on to contain bullet points of the functionality.

### CODE REVIEW

**Comment by khajavi** [comment]
@googley42  Did you update the zio-sbt plugin? How did you update the ci workflow, manually?

**Comment by googley42** [comment]
@khajavi yes I have the following in my `plugins.sbt`

```
addSbtPlugin("dev.zio"            % "zio-sbt-website" % "0.4.0-alpha.28")
addSbtPlugin("dev.zio"            % "zio-sbt-ci"      % "0.4.0-alpha.28")
```

and the CI was updated manually as I saw other projects were doing the same thing

**Review by khajavi — APPROVED** [review]

**Comment by khajavi** [comment]
If you prefer to utilize the zio-sbt plugging at the most, it is better to update the ci using zio-sbt-ci plugin, otherwise, there is no need to keep that plugin in your dependencies.

**Comment by googley42** [comment]
@khajavi one question I forgot to ask - I tried referencing an image in a doc page but local rendering server threw an exception - so my question is - how do we get images into our documentation? I see in `zio-prelude` they have used Mermade - is this the only way?

**Comment by khajavi** [comment]
How about putting images in the same directory or `./img` and referencing
them in a doc? Have you tried that? It may work, but I'm not sure!

**Comment by googley42** [comment]
I tried putting the image file in the same directory and referencing it the doc but it did not work

**Comment by khajavi** [comment]
That might be an issue that needs to be fixed. Anyway you can check and see
how zio insight works: https://zio.dev/zio-insight/

**Comment by googley42** [comment]
ah wait, tried the co-located image experiment previewed with `docs/previewWebsite` again and it worked this time - so apologies must have been a user error on my part.
Not sure what https://zio.dev/zio-insight/ is or how it could relate to rendering BTW?

**Comment by khajavi** [comment]
Good to hear!
I mean, check the documentation of zio-insight, because it has images in
its docs.

**Pull request merged**
