### PR TITLE
Introduce error hierarchy instead of String errors in DynamoDBQuery

### PR DESCRIPTION
**Pull request by morozovivan95**
This PR tries to provide a solution for #128

### CODE REVIEW

**Comment by googley42** [comment]
@morozovivan95 many thanks for you contribution which looks great! I think you need to click on the Contributor Licence Link above and click on the agree button before the PR can progress through the work flow.

**Review by googley42 — APPROVED** [review]
Many thanks for your contribution - LGTM!

However we are looking at the Website CI build problem ATM that is preventing PR builds from succeeding so please bear with us

**Comment by googley42** [comment]
hi @morozovivan95 I have disabled the Website workflow that was causing the build problems for now. If you can merge/rebase from master please and mark your PR by pressing the "Ready for Review" I can get it merged

**Comment by morozovivan95** [comment]
Hi @googley42 ! Thank you for review, I've updated the branch
Am I right creating PR against series/2.x branch? Or should it be against master?

**Comment by googley42** [comment]
yes `series-2.x` branch is the right one - I will do some cleaning up of old branches

**Comment by googley42** [comment]
merged to `series-2.x` and snapshot published - thanks for your contribution

**Pull request merged**
