### PR TITLE
Prevent Publishing Docs Submodule

### PR DESCRIPTION
**Pull request by khajavi**

### CODE REVIEW

**Comment by khajavi** [comment]
@googley42 This PR shows that the error in the `sbt +publishLocal` is probably unrelated to the recent work on the `docs` submodule.

**Comment by googley42** [comment]
@khajavi I am trying to figure out what change may have introduced the build error. It seems like there was a brief period last week when the website build stage was working https://github.com/zio/zio-dynamodb/actions/runs/3976132337 - however I am struggling to correlate github actions back to repo commits.

**Comment by googley42** [comment]
@khajavi when I removed `docs` from the aggregation in `build.sbt` `sbt publishLocal` worked so I have I left like this temporarily  so that I can get some PR's merged

**Comment by khajavi** [comment]
@googley42 
Thank you for your investigation. We can fix that issue in a separate PR.

**Pull request closed without merging**
